module.exports = {
abilities: require(__dirname + '/build/abilities.json'),
ability_ids: require(__dirname + '/build/ability_ids.json'),
ability_keys: require(__dirname + '/build/ability_keys.json'),
ancients: require(__dirname + '/build/ancients.json'),
cluster: require(__dirname + '/build/cluster.json'),
countries: require(__dirname + '/build/countries.json'),
game_mode: require(__dirname + '/build/game_mode.json'),
heroes: require(__dirname + '/build/heroes.json'),
hero_abilities: require(__dirname + '/build/hero_abilities.json'),
hero_names: require(__dirname + '/build/hero_names.json'),
items: require(__dirname + '/build/items.json'),
item_colors: require(__dirname + '/build/item_colors.json'),
item_groups: require(__dirname + '/build/item_groups.json'),
item_ids: require(__dirname + '/build/item_ids.json'),
lobby_type: require(__dirname + '/build/lobby_type.json'),
neutral_abilities: require(__dirname + '/build/neutral_abilities.json'),
order_types: require(__dirname + '/build/order_types.json'),
patch: require(__dirname + '/build/patch.json'),
permanent_buffs: require(__dirname + '/build/permanent_buffs.json'),
player_colors: require(__dirname + '/build/player_colors.json'),
region: require(__dirname + '/build/region.json'),
skillshots: require(__dirname + '/build/skillshots.json'),
xp_level: require(__dirname + '/build/xp_level.json')
};