module.exports = {
abilities: require(__dirname + "/src/data/abilities.json"),
ability_ids: require(__dirname + "/src/data/ability_ids.json"),
aghs_desc: require(__dirname + "/src/data/aghs_desc.json"),
ancients: require(__dirname + "/src/data/ancients.json"),
chat_wheel: require(__dirname + "/src/data/chat_wheel.json"),
cluster: require(__dirname + "/src/data/cluster.json"),
countries: require(__dirname + "/src/data/countries.json"),
game_mode: require(__dirname + "/src/data/game_mode.json"),
hero_abilities: require(__dirname + "/src/data/hero_abilities.json"),
hero_lore: require(__dirname + "/src/data/hero_lore.json"),
hero_names: require(__dirname + "/src/data/hero_names.json"),
heroes: require(__dirname + "/src/data/heroes.json"),
item_colors: require(__dirname + "/src/data/item_colors.json"),
item_ids: require(__dirname + "/src/data/item_ids.json"),
items: require(__dirname + "/src/data/items.json"),
lobby_type: require(__dirname + "/src/data/lobby_type.json"),
neutral_abilities: require(__dirname + "/src/data/neutral_abilities.json"),
order_types: require(__dirname + "/src/data/order_types.json"),
patch: require(__dirname + "/src/data/patch.json"),
patchnotes: require(__dirname + "/src/data/patchnotes.json"),
permanent_buffs: require(__dirname + "/src/data/permanent_buffs.json"),
player_colors: require(__dirname + "/src/data/player_colors.json"),
region: require(__dirname + "/src/data/region.json"),
skillshots: require(__dirname + "/src/data/skillshots.json"),
xp_level: require(__dirname + "/src/data/xp_level.json")
};