module.exports = {
abilities: require(__dirname + '/json/abilities.json'),
ability_ids: require(__dirname + '/json/ability_ids.json'),
ability_keys: require(__dirname + '/json/ability_keys.json'),
ancients: require(__dirname + '/json/ancients.json'),
cluster: require(__dirname + '/json/cluster.json'),
countries: require(__dirname + '/json/countries.json'),
game_mode: require(__dirname + '/json/game_mode.json'),
hero_names: require(__dirname + '/json/hero_names.json'),
heroes: require(__dirname + '/json/heroes.json'),
item_groups: require(__dirname + '/json/item_groups.json'),
item_ids: require(__dirname + '/json/item_ids.json'),
items: require(__dirname + '/json/items.json'),
lobby_type: require(__dirname + '/json/lobby_type.json'),
neutral_abilities: require(__dirname + '/json/neutral_abilities.json'),
order_types: require(__dirname + '/json/order_types.json'),
patch: require(__dirname + '/json/patch.json'),
permanent_buffs: require(__dirname + '/json/permanent_buffs.json'),
player_colors: require(__dirname + '/json/player_colors.json'),
region: require(__dirname + '/json/region.json'),
regions: require(__dirname + '/json/regions.json'),
skillshots: require(__dirname + '/json/skillshots.json'),
xp_level: require(__dirname + '/json/xp_level.json')
};